export const pageEditorId = 'pageEditorId'
export const scapholdUrl = 'scapholdUrl'
export const auth0ClientId = 'auth0ClientId'
export const auth0Domain = 'auth0Domain'
export const auth0CallbackUrl = 'auth0CallbackUrl'
